In [16]:
import pandas as pd
import os

for f in os.listdir(path):
    print(f)

teams.csv

In [17]:
import os

for f in os.listdir(path):
    print(f)

teams.csv

In [18]:
df = pd.read_csv(f"{path}/teams.csv")

In [20]:
df.shape

(48, 136)

In [21]:
display(df)

,team,team_country,players_used,avg_age,possession,games,games_starts,minutes,minutes_90s,goals,...,gk_wins_against,gk_ties_against,gk_losses_against,gk_clean_sheets_against,gk_clean_sheets_pct_against,gk_pens_att_against,gk_pens_allowed_against,gk_pens_saved_against,gk_pens_missed_against,gk_pens_save_pct_against
0,Algeria,Algeria,19,27.4,62.0,2,22,180,2.0,2,...,1,0,1,1,50.0,0,0,0,0,NaN
1,Argentina,Argentina,18,29.7,51.0,2,22,180,2.0,5,...,0,0,2,0,0.0,1,0,0,1,NaN
2,Australia,Australia,20,25.6,40.7,3,33,270,3.0,2,...,1,1,1,2,66.7,0,0,0,0,NaN
3,Austria,Austria,19,29.0,54.5,2,22,180,2.0,2,...,1,0,1,1,50.0,1,1,0,0,0.0
4,Belgium,Belgium,19,29.8,59.7,3,33,270,3.0,5,...,0,2,1,1,33.3,0,0,0,0,NaN
5,Bosnia & Herz.,Bosnia and Herzegovina,22,26.9,44.0,3,33,270,3.0,4,...,1,1,1,0,0.0,0,0,0,0,NaN
6,Brazil,Brazil,22,29.8,54.0,3,33,270,3.0,7,...,0,1,2,0,0.0,0,0,0,0,NaN
7,Cabo Verde,Cape Verde,21,31.2,37.3,3,33,270,3.0,2,...,0,3,0,2,66.7,0,0,0,0,NaN
8,Canada,Canada,20,27.4,61.7,3,33,270,3.0,7,...,1,1,1,0,0.0,0,0,0,0,NaN
9,Colombia,Colombia,18,30.5,63.0,2,22,180,2.0,4,...,0,0,2,0,0.0,0,0,0,0,NaN
10,Congo DR,Congo DR,17,29.5,31.0,2,22,180,2.0,1,...,1,1,0,1,50.0,0,0,0,0,NaN
11,Croatia,Croatia,19,29.1,53.0,2,22,180,2.0,3,...,1,0,1,0,0.0,0,0,0,0,NaN
12,Curaçao,Curaçao,22,29.3,32.3,3,33,270,3.0,1,...,2,1,0,2,66.7,0,0,0,0,NaN
13,Czechia,Czech Republic,21,28.2,42.7,3,33,270,3.0,2,...,2,1,0,1,33.3,0,0,0,0,NaN
14,Côte d'Ivoire,Côte d'Ivoire,22,25.8,50.7,3,33,270,3.0,4,...,1,0,2,0,0.0,0,0,0,0,NaN
15,Ecuador,Ecuador,19,27.3,55.3,3,33,270,3.0,2,...,1,1,1,2,66.7,0,0,0,0,NaN
16,Egypt,Egypt,20,29.6,54.3,3,33,270,3.0,5,...,0,2,1,0,0.0,0,0,0,0,NaN
17,England,England,17,27.0,65.5,2,22,180,2.0,4,...,0,1,1,1,50.0,1,1,0,0,0.0
18,France,France,21,27.1,55.7,3,33,270,3.0,10,...,0,0,3,0,0.0,0,0,0,0,NaN
19,Germany,Germany,22,28.4,61.7,3,33,270,3.0,10,...,1,0,2,0,0.0,1,1,0,0,0.0
20,Ghana,Ghana,20,27.2,29.5,2,22,180,2.0,1,...,0,1,1,1,50.0,0,0,0,0,NaN
21,Haiti,Haiti,18,29.0,42.7,3,33,270,3.0,1,...,3,0,0,2,66.7,0,0,0,0,NaN
22,IR Iran,Iran,20,32.1,39.0,3,33,270,3.0,3,...,0,3,0,1,33.3,1,0,1,0,100.0
23,Iraq,Iraq,25,26.8,38.3,3,33,270,3.0,1,...,3,0,0,2,66.7,0,0,0,0,NaN
24,Japan,Japan,23,27.9,51.3,3,33,270,3.0,7,...,0,2,1,0,0.0,0,0,0,0,NaN
25,Jordan,Jordan,19,28.8,32.5,2,22,180,2.0,2,...,2,0,0,0,0.0,0,0,0,0,NaN
26,Korea Republic,Korea Republic,20,28.6,63.0,3,33,270,3.0,2,...,2,0,1,2,66.7,0,0,0,0,NaN
27,Mexico,Mexico,25,27.9,50.3,3,33,270,3.0,6,...,0,0,3,0,0.0,0,0,0,0,NaN
28,Morocco,Morocco,20,26.3,59.0,3,33,270,3.0,6,...,0,1,2,0,0.0,0,0,0,0,NaN
29,Netherlands,Netherlands,19,27.6,61.0,3,33,270,3.0,9,...,0,1,2,0,0.0,0,0,0,0,NaN
30,New Zealand,New Zealand,17,28.5,47.0,3,33,270,3.0,4,...,2,1,0,0,0.0,0,0,0,0,NaN
31,Norway,Norway,25,27.3,48.7,3,33,270,3.0,7,...,1,0,2,0,0.0,1,0,1,0,100.0
32,Panama,Panama,17,29.3,52.0,2,22,180,2.0,0,...,2,0,0,2,100.0,0,0,0,0,NaN
33,Paraguay,Paraguay,21,28.1,33.7,3,33,270,3.0,2,...,1,1,1,1,33.3,0,0,0,0,NaN
34,Portugal,Portugal,18,28.0,70.5,2,22,180,2.0,5,...,0,1,1,0,0.0,0,0,0,0,NaN
35,Qatar,Qatar,22,30.1,33.0,3,33,270,3.0,2,...,2,1,0,1,33.3,0,0,0,0,NaN
36,Saudi Arabia,Saudi Arabia,18,29.0,38.3,3,33,270,3.0,1,...,1,2,0,2,66.7,0,0,0,0,NaN
37,Scotland,Scotland,20,29.5,44.3,3,33,270,3.0,1,...,2,0,1,2,66.7,0,0,0,0,NaN
38,Senegal,Senegal,21,29.1,57.7,3,33,270,3.0,8,...,2,0,1,0,0.0,0,0,0,0,NaN
39,South Africa,South Africa,19,27.2,44.7,3,33,270,3.0,2,...,1,1,1,1,33.3,1,1,0,0,0.0
40,Spain,Spain,18,27.0,69.3,3,33,270,3.0,4,...,0,1,2,1,33.3,0,0,0,0,NaN
41,Sweden,Sweden,21,27.4,48.7,3,33,270,3.0,7,...,1,1,1,0,0.0,0,0,0,0,NaN
42,Switzerland,Switzerland,21,29.9,61.7,3,33,270,3.0,7,...,0,1,2,0,0.0,2,2,0,0,0.0
43,Tunisia,Tunisia,20,27.8,39.3,3,33,270,3.0,2,...,3,0,0,1,33.3,0,0,0,0,NaN
44,Türkiye,Turkey,23,27.0,66.3,3,33,270,3.0,3,...,2,0,1,2,66.7,0,0,0,0,NaN
45,United States,United States,23,27.0,60.0,3,33,270,3.0,6,...,1,0,2,0,0.0,0,0,0,0,NaN
46,Uruguay,Uruguay,17,29.0,55.0,3,33,270,3.0,3,...,1,2,0,1,33.3,0,0,0,0,NaN
47,Uzbekistan,Uzbekistan,22,27.4,36.5,2,22,180,2.0,1,...,2,0,0,1,50.0,0,0,0,0,NaN

In [22]:
rename_map = {

    'team':            'time',
    'team_country':    'país',
    'players_used':    'jogadores_utilizados',
    'avg_age':         'idade_média',
    'possession':      'posse_de_bola',
    'games':           'jogos',
    'games_starts':    'titulares',
    'minutes':         'minutos',
    'minutes_90s':     'minutos_90',
    'goals':           'gols',

    'gk_wins_against':              'gol_vitórias_adversário',
    'gk_ties_against':              'gol_empates_adversário',
    'gk_losses_against':            'gol_derrotas_adversário',
    'gk_clean_sheets_against':      'gol_jogos_sem_tomar_gol',
    'gk_clean_sheets_pct_against':  'gol_pct_sem_tomar_gol',
    'gk_pens_att_against':          'gol_pênaltis_sofridos',
    'gk_pens_allowed_against':      'gol_pênaltis_convertidos',
    'gk_pens_saved_against':        'gol_pênaltis_defendidos',
    'gk_pens_missed_against':       'gol_pênaltis_perdidos',
    'gk_pens_save_pct_against':     'gol_pct_defesas_pênaltis',
}

df.rename(columns=rename_map, inplace=True)

,time,país,jogadores_utilizados,idade_média,posse_de_bola,jogos,titulares,minutos,minutos_90,gols,...,gol_vitórias_adversário,gol_empates_adversário,gol_derrotas_adversário,gol_jogos_sem_tomar_gol,gol_pct_sem_tomar_gol,gol_pênaltis_sofridos,gol_pênaltis_convertidos,gol_pênaltis_defendidos,gol_pênaltis_perdidos,gol_pct_defesas_pênaltis
0,Algeria,Algeria,19,27.4,62.0,2,22,180,2.0,2,...,1,0,1,1,50.0,0,0,0,0,NaN
1,Argentina,Argentina,18,29.7,51.0,2,22,180,2.0,5,...,0,0,2,0,0.0,1,0,0,1,NaN
2,Australia,Australia,20,25.6,40.7,3,33,270,3.0,2,...,1,1,1,2,66.7,0,0,0,0,NaN
3,Austria,Austria,19,29.0,54.5,2,22,180,2.0,2,...,1,0,1,1,50.0,1,1,0,0,0.0
4,Belgium,Belgium,19,29.8,59.7,3,33,270,3.0,5,...,0,2,1,1,33.3,0,0,0,0,NaN

In [24]:
display(df)

,time,país,jogadores_utilizados,idade_média,posse_de_bola,jogos,titulares,minutos,minutos_90,gols,...,gol_vitórias_adversário,gol_empates_adversário,gol_derrotas_adversário,gol_jogos_sem_tomar_gol,gol_pct_sem_tomar_gol,gol_pênaltis_sofridos,gol_pênaltis_convertidos,gol_pênaltis_defendidos,gol_pênaltis_perdidos,gol_pct_defesas_pênaltis
0,Algeria,Algeria,19,27.4,62.0,2,22,180,2.0,2,...,1,0,1,1,50.0,0,0,0,0,NaN
1,Argentina,Argentina,18,29.7,51.0,2,22,180,2.0,5,...,0,0,2,0,0.0,1,0,0,1,NaN
2,Australia,Australia,20,25.6,40.7,3,33,270,3.0,2,...,1,1,1,2,66.7,0,0,0,0,NaN
3,Austria,Austria,19,29.0,54.5,2,22,180,2.0,2,...,1,0,1,1,50.0,1,1,0,0,0.0
4,Belgium,Belgium,19,29.8,59.7,3,33,270,3.0,5,...,0,2,1,1,33.3,0,0,0,0,NaN
5,Bosnia & Herz.,Bosnia and Herzegovina,22,26.9,44.0,3,33,270,3.0,4,...,1,1,1,0,0.0,0,0,0,0,NaN
6,Brazil,Brazil,22,29.8,54.0,3,33,270,3.0,7,...,0,1,2,0,0.0,0,0,0,0,NaN
7,Cabo Verde,Cape Verde,21,31.2,37.3,3,33,270,3.0,2,...,0,3,0,2,66.7,0,0,0,0,NaN
8,Canada,Canada,20,27.4,61.7,3,33,270,3.0,7,...,1,1,1,0,0.0,0,0,0,0,NaN
9,Colombia,Colombia,18,30.5,63.0,2,22,180,2.0,4,...,0,0,2,0,0.0,0,0,0,0,NaN
10,Congo DR,Congo DR,17,29.5,31.0,2,22,180,2.0,1,...,1,1,0,1,50.0,0,0,0,0,NaN
11,Croatia,Croatia,19,29.1,53.0,2,22,180,2.0,3,...,1,0,1,0,0.0,0,0,0,0,NaN
12,Curaçao,Curaçao,22,29.3,32.3,3,33,270,3.0,1,...,2,1,0,2,66.7,0,0,0,0,NaN
13,Czechia,Czech Republic,21,28.2,42.7,3,33,270,3.0,2,...,2,1,0,1,33.3,0,0,0,0,NaN
14,Côte d'Ivoire,Côte d'Ivoire,22,25.8,50.7,3,33,270,3.0,4,...,1,0,2,0,0.0,0,0,0,0,NaN
15,Ecuador,Ecuador,19,27.3,55.3,3,33,270,3.0,2,...,1,1,1,2,66.7,0,0,0,0,NaN
16,Egypt,Egypt,20,29.6,54.3,3,33,270,3.0,5,...,0,2,1,0,0.0,0,0,0,0,NaN
17,England,England,17,27.0,65.5,2,22,180,2.0,4,...,0,1,1,1,50.0,1,1,0,0,0.0
18,France,France,21,27.1,55.7,3,33,270,3.0,10,...,0,0,3,0,0.0,0,0,0,0,NaN
19,Germany,Germany,22,28.4,61.7,3,33,270,3.0,10,...,1,0,2,0,0.0,1,1,0,0,0.0
20,Ghana,Ghana,20,27.2,29.5,2,22,180,2.0,1,...,0,1,1,1,50.0,0,0,0,0,NaN
21,Haiti,Haiti,18,29.0,42.7,3,33,270,3.0,1,...,3,0,0,2,66.7,0,0,0,0,NaN
22,IR Iran,Iran,20,32.1,39.0,3,33,270,3.0,3,...,0,3,0,1,33.3,1,0,1,0,100.0
23,Iraq,Iraq,25,26.8,38.3,3,33,270,3.0,1,...,3,0,0,2,66.7,0,0,0,0,NaN
24,Japan,Japan,23,27.9,51.3,3,33,270,3.0,7,...,0,2,1,0,0.0,0,0,0,0,NaN
25,Jordan,Jordan,19,28.8,32.5,2,22,180,2.0,2,...,2,0,0,0,0.0,0,0,0,0,NaN
26,Korea Republic,Korea Republic,20,28.6,63.0,3,33,270,3.0,2,...,2,0,1,2,66.7,0,0,0,0,NaN
27,Mexico,Mexico,25,27.9,50.3,3,33,270,3.0,6,...,0,0,3,0,0.0,0,0,0,0,NaN
28,Morocco,Morocco,20,26.3,59.0,3,33,270,3.0,6,...,0,1,2,0,0.0,0,0,0,0,NaN
29,Netherlands,Netherlands,19,27.6,61.0,3,33,270,3.0,9,...,0,1,2,0,0.0,0,0,0,0,NaN
30,New Zealand,New Zealand,17,28.5,47.0,3,33,270,3.0,4,...,2,1,0,0,0.0,0,0,0,0,NaN
31,Norway,Norway,25,27.3,48.7,3,33,270,3.0,7,...,1,0,2,0,0.0,1,0,1,0,100.0
32,Panama,Panama,17,29.3,52.0,2,22,180,2.0,0,...,2,0,0,2,100.0,0,0,0,0,NaN
33,Paraguay,Paraguay,21,28.1,33.7,3,33,270,3.0,2,...,1,1,1,1,33.3,0,0,0,0,NaN
34,Portugal,Portugal,18,28.0,70.5,2,22,180,2.0,5,...,0,1,1,0,0.0,0,0,0,0,NaN
35,Qatar,Qatar,22,30.1,33.0,3,33,270,3.0,2,...,2,1,0,1,33.3,0,0,0,0,NaN
36,Saudi Arabia,Saudi Arabia,18,29.0,38.3,3,33,270,3.0,1,...,1,2,0,2,66.7,0,0,0,0,NaN
37,Scotland,Scotland,20,29.5,44.3,3,33,270,3.0,1,...,2,0,1,2,66.7,0,0,0,0,NaN
38,Senegal,Senegal,21,29.1,57.7,3,33,270,3.0,8,...,2,0,1,0,0.0,0,0,0,0,NaN
39,South Africa,South Africa,19,27.2,44.7,3,33,270,3.0,2,...,1,1,1,1,33.3,1,1,0,0,0.0
40,Spain,Spain,18,27.0,69.3,3,33,270,3.0,4,...,0,1,2,1,33.3,0,0,0,0,NaN
41,Sweden,Sweden,21,27.4,48.7,3,33,270,3.0,7,...,1,1,1,0,0.0,0,0,0,0,NaN
42,Switzerland,Switzerland,21,29.9,61.7,3,33,270,3.0,7,...,0,1,2,0,0.0,2,2,0,0,0.0
43,Tunisia,Tunisia,20,27.8,39.3,3,33,270,3.0,2,...,3,0,0,1,33.3,0,0,0,0,NaN
44,Türkiye,Turkey,23,27.0,66.3,3,33,270,3.0,3,...,2,0,1,2,66.7,0,0,0,0,NaN
45,United States,United States,23,27.0,60.0,3,33,270,3.0,6,...,1,0,2,0,0.0,0,0,0,0,NaN
46,Uruguay,Uruguay,17,29.0,55.0,3,33,270,3.0,3,...,1,2,0,1,33.3,0,0,0,0,NaN
47,Uzbekistan,Uzbekistan,22,27.4,36.5,2,22,180,2.0,1,...,2,0,0,1,50.0,0,0,0,0,NaN

In [25]:
print(df.columns.tolist())

['time', 'país', 'jogadores_utilizados', 'idade_média', 'posse_de_bola', 'jogos', 'titulares', 'minutos', 'minutos_90', 'gols', 'assists', 'goals_assists', 'goals_pens', 'pens_made', 'pens_att', 'cards_yellow', 'cards_red', 'goals_per90', 'assists_per90', 'goals_assists_per90', 'goals_pens_per90', 'goals_assists_pens_per90', 'players_used_against', 'avg_age_against', 'possession_against', 'games_against', 'games_starts_against', 'minutes_against', 'minutes_90s_against', 'goals_against', 'assists_against', 'goals_assists_against', 'goals_pens_against', 'pens_made_against', 'pens_att_against', 'cards_yellow_against', 'cards_red_against', 'goals_per90_against', 'assists_per90_against', 'goals_assists_per90_against', 'goals_pens_per90_against', 'goals_assists_pens_per90_against', 'shots', 'shots_on_target', 'shots_on_target_pct', 'shots_per90', 'shots_on_target_per90', 'goals_per_shot', 'goals_per_shot_on_target', 'shots_against', 'shots_on_target_against', 'shots_on_target_pct_against', 'shots_per90_against', 'shots_on_target_per90_against', 'goals_per_shot_against', 'goals_per_shot_on_target_against', 'minutes_per_game', 'minutes_pct', 'minutes_per_start', 'games_complete', 'games_subs', 'minutes_per_sub', 'unused_subs', 'points_per_game', 'on_goals_for', 'on_goals_against', 'plus_minus', 'plus_minus_per90', 'minutes_per_game_against', 'minutes_pct_against', 'minutes_per_start_against', 'games_complete_against', 'games_subs_against', 'minutes_per_sub_against', 'unused_subs_against', 'points_per_game_against', 'on_goals_for_against', 'on_goals_against_against', 'plus_minus_against', 'plus_minus_per90_against', 'cards_yellow_red', 'fouls', 'fouled', 'offsides', 'crosses', 'interceptions', 'tackles_won', 'pens_won', 'pens_conceded', 'own_goals', 'cards_yellow_red_against', 'fouls_against', 'fouled_against', 'offsides_against', 'crosses_against', 'interceptions_against', 'tackles_won_against', 'pens_won_against', 'pens_conceded_against', 'own_goals_against', 'gk_games', 'gk_games_starts', 'gk_minutes', 'gk_goals_against', 'gk_goals_against_per90', 'gk_shots_on_target_against', 'gk_saves', 'gk_save_pct', 'gk_wins', 'gk_ties', 'gk_losses', 'gk_clean_sheets', 'gk_clean_sheets_pct', 'gk_pens_att', 'gk_pens_allowed', 'gk_pens_saved', 'gk_pens_missed', 'gk_pens_save_pct', 'gk_games_against', 'gk_games_starts_against', 'gk_minutes_against', 'gk_goals_against_against', 'gk_goals_against_per90_against', 'gk_shots_on_target_against_against', 'gk_saves_against', 'gk_save_pct_against', 'gol_vitórias_adversário', 'gol_empates_adversário', 'gol_derrotas_adversário', 'gol_jogos_sem_tomar_gol', 'gol_pct_sem_tomar_gol', 'gol_pênaltis_sofridos', 'gol_pênaltis_convertidos', 'gol_pênaltis_defendidos', 'gol_pênaltis_perdidos', 'gol_pct_defesas_pênaltis']

In [26]:
rename_map = {
    # Ataque — próprio time
    'assists':                          'assistencias',
    'goals_assists':                    'gols_e_assistencias',
    'goals_pens':                       'gols_sem_penalti',
    'pens_made':                        'penaltis_convertidos',
    'pens_att':                         'penaltis_cobrados',
    'cards_yellow':                     'cartoes_amarelos',
    'cards_red':                        'cartoes_vermelhos',
    'goals_per90':                      'gols_por_90',
    'assists_per90':                    'assistencias_por_90',
    'goals_assists_per90':              'gols_assist_por_90',
    'goals_pens_per90':                 'gols_sem_pen_por_90',
    'goals_assists_pens_per90':         'gols_assist_sem_pen_por_90',

    # Geral — adversário
    'players_used_against':             'jogadores_usados_adv',
    'avg_age_against':                  'idade_media_adv',
    'possession_against':               'posse_bola_adv',
    'games_against':                    'jogos_adv',
    'games_starts_against':             'titulares_adv',
    'minutes_against':                  'minutos_adv',
    'minutes_90s_against':              'minutos_90_adv',
    'goals_against':                    'gols_adv',
    'assists_against':                  'assistencias_adv',
    'goals_assists_against':            'gols_e_assist_adv',
    'goals_pens_against':               'gols_sem_pen_adv',
    'pens_made_against':                'penaltis_conv_adv',
    'pens_att_against':                 'penaltis_cobrados_adv',
    'cards_yellow_against':             'cartoes_amarelos_adv',
    'cards_red_against':                'cartoes_vermelhos_adv',
    'goals_per90_against':              'gols_por_90_adv',
    'assists_per90_against':            'assist_por_90_adv',
    'goals_assists_per90_against':      'gols_assist_por_90_adv',
    'goals_pens_per90_against':         'gols_sem_pen_90_adv',
    'goals_assists_pens_per90_against': 'gols_assist_sem_pen_90_adv',

    # Finalizações — próprio time
    'shots':                            'chutes',
    'shots_on_target':                  'chutes_no_alvo',
    'shots_on_target_pct':              'pct_chutes_no_alvo',
    'shots_per90':                      'chutes_por_90',
    'shots_on_target_per90':            'chutes_alvo_por_90',
    'goals_per_shot':                   'gols_por_chute',
    'goals_per_shot_on_target':         'gols_por_chute_no_alvo',

    # Finalizações — adversário
    'shots_against':                    'chutes_adv',
    'shots_on_target_against':          'chutes_no_alvo_adv',
    'shots_on_target_pct_against':      'pct_chutes_no_alvo_adv',
    'shots_per90_against':              'chutes_por_90_adv',
    'shots_on_target_per90_against':    'chutes_alvo_por_90_adv',
    'goals_per_shot_against':           'gols_por_chute_adv',
    'goals_per_shot_on_target_against': 'gols_por_chute_alvo_adv',

    # Utilização — próprio time
    'minutes_per_game':                 'minutos_por_jogo',
    'minutes_pct':                      'pct_minutos_jogados',
    'minutes_per_start':                'minutos_por_partida_titular',
    'games_complete':                   'jogos_completos',
    'games_subs':                       'entradas_como_sub',
    'minutes_per_sub':                  'minutos_por_sub',
    'unused_subs':                      'reservas_nao_usados',
    'points_per_game':                  'pontos_por_jogo',
    'on_goals_for':                     'gols_favor_em_campo',
    'on_goals_against':                 'gols_contra_em_campo',
    'plus_minus':                       'saldo_gols',
    'plus_minus_per90':                 'saldo_gols_por_90',

    # Utilização — adversário
    'minutes_per_game_against':         'minutos_por_jogo_adv',
    'minutes_pct_against':              'pct_minutos_adv',
    'minutes_per_start_against':        'minutos_por_titular_adv',
    'games_complete_against':           'jogos_completos_adv',
    'games_subs_against':               'entradas_como_sub_adv',
    'minutes_per_sub_against':          'minutos_por_sub_adv',
    'unused_subs_against':              'reservas_nao_usados_adv',
    'points_per_game_against':          'pontos_por_jogo_adv',
    'on_goals_for_against':             'gols_favor_em_campo_adv',
    'on_goals_against_against':         'gols_contra_em_campo_adv',
    'plus_minus_against':               'saldo_gols_adv',
    'plus_minus_per90_against':         'saldo_gols_por_90_adv',

    # Disciplina e ações — próprio time
    'cards_yellow_red':                 'cartoes_amarelo_vermelho',
    'fouls':                            'faltas_cometidas',
    'fouled':                           'faltas_sofridas',
    'offsides':                         'impedimentos',
    'crosses':                          'cruzamentos',
    'interceptions':                    'interceptacoes',
    'tackles_won':                      'desarmes_vencidos',
    'pens_won':                         'penaltis_ganhos',
    'pens_conceded':                    'penaltis_cedidos',
    'own_goals':                        'gols_contra',

    # Disciplina e ações — adversário
    'cards_yellow_red_against':         'cartoes_am_verm_adv',
    'fouls_against':                    'faltas_cometidas_adv',
    'fouled_against':                   'faltas_sofridas_adv',
    'offsides_against':                 'impedimentos_adv',
    'crosses_against':                  'cruzamentos_adv',
    'interceptions_against':            'interceptacoes_adv',
    'tackles_won_against':              'desarmes_vencidos_adv',
    'pens_won_against':                 'penaltis_ganhos_adv',
    'pens_conceded_against':            'penaltis_cedidos_adv',
    'own_goals_against':                'gols_contra_adv',

    # Goleiro — próprio time
    'gk_games':                         'gol_jogos',
    'gk_games_starts':                  'gol_partidas_titular',
    'gk_minutes':                       'gol_minutos',
    'gk_goals_against':                 'gol_gols_sofridos',
    'gk_goals_against_per90':           'gol_gols_sofridos_por_90',
    'gk_shots_on_target_against':       'gol_finalizacoes_sofridas',
    'gk_saves':                         'gol_defesas',
    'gk_save_pct':                      'gol_pct_defesas',
    'gk_wins':                          'gol_vitorias',
    'gk_ties':                          'gol_empates_gol',
    'gk_losses':                        'gol_derrotas_gol',
    'gk_clean_sheets':                  'gol_jogos_zerados',
    'gk_clean_sheets_pct':              'gol_pct_jogos_zerados',
    'gk_pens_att':                      'gol_penaltis_enfrentados',
    'gk_pens_allowed':                  'gol_penaltis_sofridos_gol',
    'gk_pens_saved':                    'gol_penaltis_parados',
    'gk_pens_missed':                   'gol_penaltis_errados_adv',
    'gk_pens_save_pct':                 'gol_pct_defesas_pen',

    # Goleiro — adversário
    'gk_games_against':                 'gol_jogos_adv',
    'gk_games_starts_against':          'gol_partidas_titular_adv',
    'gk_minutes_against':               'gol_minutos_adv',
    'gk_goals_against_against':         'gol_gols_sofridos_adv',
    'gk_goals_against_per90_against':   'gol_gols_sofridos_90_adv',
    'gk_shots_on_target_against_against': 'gol_finalizacoes_sofridas_adv',
    'gk_saves_against':                 'gol_defesas_adv',
    'gk_save_pct_against':              'gol_pct_defesas_adv',
}

df.rename(columns=rename_map, inplace=True)

# Confirma que não sobrou nada em inglês
restantes = [c for c in df.columns if c.isascii() and c.replace('_','').isalpha()]
print("Colunas ainda em inglês:", restantes)

Colunas ainda em inglês: ['time', 'jogadores_utilizados', 'posse_de_bola', 'jogos', 'titulares', 'minutos', 'gols', 'assistencias', 'gols_e_assistencias', 'gols_sem_penalti', 'penaltis_convertidos', 'penaltis_cobrados', 'cartoes_amarelos', 'cartoes_vermelhos', 'jogadores_usados_adv', 'idade_media_adv', 'posse_bola_adv', 'jogos_adv', 'titulares_adv', 'minutos_adv', 'gols_adv', 'assistencias_adv', 'gols_e_assist_adv', 'gols_sem_pen_adv', 'penaltis_conv_adv', 'penaltis_cobrados_adv', 'cartoes_amarelos_adv', 'cartoes_vermelhos_adv', 'chutes', 'chutes_no_alvo', 'pct_chutes_no_alvo', 'gols_por_chute', 'gols_por_chute_no_alvo', 'chutes_adv', 'chutes_no_alvo_adv', 'pct_chutes_no_alvo_adv', 'gols_por_chute_adv', 'gols_por_chute_alvo_adv', 'minutos_por_jogo', 'pct_minutos_jogados', 'minutos_por_partida_titular', 'jogos_completos', 'entradas_como_sub', 'minutos_por_sub', 'reservas_nao_usados', 'pontos_por_jogo', 'gols_favor_em_campo', 'gols_contra_em_campo', 'saldo_gols', 'minutos_por_jogo_adv', 'pct_minutos_adv', 'minutos_por_titular_adv', 'jogos_completos_adv', 'entradas_como_sub_adv', 'minutos_por_sub_adv', 'reservas_nao_usados_adv', 'pontos_por_jogo_adv', 'gols_favor_em_campo_adv', 'gols_contra_em_campo_adv', 'saldo_gols_adv', 'cartoes_amarelo_vermelho', 'faltas_cometidas', 'faltas_sofridas', 'impedimentos', 'cruzamentos', 'interceptacoes', 'desarmes_vencidos', 'penaltis_ganhos', 'penaltis_cedidos', 'gols_contra', 'cartoes_am_verm_adv', 'faltas_cometidas_adv', 'faltas_sofridas_adv', 'impedimentos_adv', 'cruzamentos_adv', 'interceptacoes_adv', 'desarmes_vencidos_adv', 'penaltis_ganhos_adv', 'penaltis_cedidos_adv', 'gols_contra_adv', 'gol_jogos', 'gol_partidas_titular', 'gol_minutos', 'gol_gols_sofridos', 'gol_finalizacoes_sofridas', 'gol_defesas', 'gol_pct_defesas', 'gol_vitorias', 'gol_empates_gol', 'gol_derrotas_gol', 'gol_jogos_zerados', 'gol_pct_jogos_zerados', 'gol_penaltis_enfrentados', 'gol_penaltis_sofridos_gol', 'gol_penaltis_parados', 'gol_penaltis_errados_adv', 'gol_pct_defesas_pen', 'gol_jogos_adv', 'gol_partidas_titular_adv', 'gol_minutos_adv', 'gol_gols_sofridos_adv', 'gol_finalizacoes_sofridas_adv', 'gol_defesas_adv', 'gol_pct_defesas_adv', 'gol_jogos_sem_tomar_gol', 'gol_pct_sem_tomar_gol']

In [27]:
df.shape

(48, 136)

In [28]:
df

,time,país,jogadores_utilizados,idade_média,posse_de_bola,jogos,titulares,minutos,minutos_90,gols,...,gol_vitórias_adversário,gol_empates_adversário,gol_derrotas_adversário,gol_jogos_sem_tomar_gol,gol_pct_sem_tomar_gol,gol_pênaltis_sofridos,gol_pênaltis_convertidos,gol_pênaltis_defendidos,gol_pênaltis_perdidos,gol_pct_defesas_pênaltis
0,Algeria,Algeria,19,27.4,62.0,2,22,180,2.0,2,...,1,0,1,1,50.0,0,0,0,0,NaN
1,Argentina,Argentina,18,29.7,51.0,2,22,180,2.0,5,...,0,0,2,0,0.0,1,0,0,1,NaN
2,Australia,Australia,20,25.6,40.7,3,33,270,3.0,2,...,1,1,1,2,66.7,0,0,0,0,NaN
3,Austria,Austria,19,29.0,54.5,2,22,180,2.0,2,...,1,0,1,1,50.0,1,1,0,0,0.0
4,Belgium,Belgium,19,29.8,59.7,3,33,270,3.0,5,...,0,2,1,1,33.3,0,0,0,0,NaN
5,Bosnia & Herz.,Bosnia and Herzegovina,22,26.9,44.0,3,33,270,3.0,4,...,1,1,1,0,0.0,0,0,0,0,NaN
6,Brazil,Brazil,22,29.8,54.0,3,33,270,3.0,7,...,0,1,2,0,0.0,0,0,0,0,NaN
7,Cabo Verde,Cape Verde,21,31.2,37.3,3,33,270,3.0,2,...,0,3,0,2,66.7,0,0,0,0,NaN
8,Canada,Canada,20,27.4,61.7,3,33,270,3.0,7,...,1,1,1,0,0.0,0,0,0,0,NaN
9,Colombia,Colombia,18,30.5,63.0,2,22,180,2.0,4,...,0,0,2,0,0.0,0,0,0,0,NaN
10,Congo DR,Congo DR,17,29.5,31.0,2,22,180,2.0,1,...,1,1,0,1,50.0,0,0,0,0,NaN
11,Croatia,Croatia,19,29.1,53.0,2,22,180,2.0,3,...,1,0,1,0,0.0,0,0,0,0,NaN
12,Curaçao,Curaçao,22,29.3,32.3,3,33,270,3.0,1,...,2,1,0,2,66.7,0,0,0,0,NaN
13,Czechia,Czech Republic,21,28.2,42.7,3,33,270,3.0,2,...,2,1,0,1,33.3,0,0,0,0,NaN
14,Côte d'Ivoire,Côte d'Ivoire,22,25.8,50.7,3,33,270,3.0,4,...,1,0,2,0,0.0,0,0,0,0,NaN
15,Ecuador,Ecuador,19,27.3,55.3,3,33,270,3.0,2,...,1,1,1,2,66.7,0,0,0,0,NaN
16,Egypt,Egypt,20,29.6,54.3,3,33,270,3.0,5,...,0,2,1,0,0.0,0,0,0,0,NaN
17,England,England,17,27.0,65.5,2,22,180,2.0,4,...,0,1,1,1,50.0,1,1,0,0,0.0
18,France,France,21,27.1,55.7,3,33,270,3.0,10,...,0,0,3,0,0.0,0,0,0,0,NaN
19,Germany,Germany,22,28.4,61.7,3,33,270,3.0,10,...,1,0,2,0,0.0,1,1,0,0,0.0
20,Ghana,Ghana,20,27.2,29.5,2,22,180,2.0,1,...,0,1,1,1,50.0,0,0,0,0,NaN
21,Haiti,Haiti,18,29.0,42.7,3,33,270,3.0,1,...,3,0,0,2,66.7,0,0,0,0,NaN
22,IR Iran,Iran,20,32.1,39.0,3,33,270,3.0,3,...,0,3,0,1,33.3,1,0,1,0,100.0
23,Iraq,Iraq,25,26.8,38.3,3,33,270,3.0,1,...,3,0,0,2,66.7,0,0,0,0,NaN
24,Japan,Japan,23,27.9,51.3,3,33,270,3.0,7,...,0,2,1,0,0.0,0,0,0,0,NaN
25,Jordan,Jordan,19,28.8,32.5,2,22,180,2.0,2,...,2,0,0,0,0.0,0,0,0,0,NaN
26,Korea Republic,Korea Republic,20,28.6,63.0,3,33,270,3.0,2,...,2,0,1,2,66.7,0,0,0,0,NaN
27,Mexico,Mexico,25,27.9,50.3,3,33,270,3.0,6,...,0,0,3,0,0.0,0,0,0,0,NaN
28,Morocco,Morocco,20,26.3,59.0,3,33,270,3.0,6,...,0,1,2,0,0.0,0,0,0,0,NaN
29,Netherlands,Netherlands,19,27.6,61.0,3,33,270,3.0,9,...,0,1,2,0,0.0,0,0,0,0,NaN
30,New Zealand,New Zealand,17,28.5,47.0,3,33,270,3.0,4,...,2,1,0,0,0.0,0,0,0,0,NaN
31,Norway,Norway,25,27.3,48.7,3,33,270,3.0,7,...,1,0,2,0,0.0,1,0,1,0,100.0
32,Panama,Panama,17,29.3,52.0,2,22,180,2.0,0,...,2,0,0,2,100.0,0,0,0,0,NaN
33,Paraguay,Paraguay,21,28.1,33.7,3,33,270,3.0,2,...,1,1,1,1,33.3,0,0,0,0,NaN
34,Portugal,Portugal,18,28.0,70.5,2,22,180,2.0,5,...,0,1,1,0,0.0,0,0,0,0,NaN
35,Qatar,Qatar,22,30.1,33.0,3,33,270,3.0,2,...,2,1,0,1,33.3,0,0,0,0,NaN
36,Saudi Arabia,Saudi Arabia,18,29.0,38.3,3,33,270,3.0,1,...,1,2,0,2,66.7,0,0,0,0,NaN
37,Scotland,Scotland,20,29.5,44.3,3,33,270,3.0,1,...,2,0,1,2,66.7,0,0,0,0,NaN
38,Senegal,Senegal,21,29.1,57.7,3,33,270,3.0,8,...,2,0,1,0,0.0,0,0,0,0,NaN
39,South Africa,South Africa,19,27.2,44.7,3,33,270,3.0,2,...,1,1,1,1,33.3,1,1,0,0,0.0
40,Spain,Spain,18,27.0,69.3,3,33,270,3.0,4,...,0,1,2,1,33.3,0,0,0,0,NaN
41,Sweden,Sweden,21,27.4,48.7,3,33,270,3.0,7,...,1,1,1,0,0.0,0,0,0,0,NaN
42,Switzerland,Switzerland,21,29.9,61.7,3,33,270,3.0,7,...,0,1,2,0,0.0,2,2,0,0,0.0
43,Tunisia,Tunisia,20,27.8,39.3,3,33,270,3.0,2,...,3,0,0,1,33.3,0,0,0,0,NaN
44,Türkiye,Turkey,23,27.0,66.3,3,33,270,3.0,3,...,2,0,1,2,66.7,0,0,0,0,NaN
45,United States,United States,23,27.0,60.0,3,33,270,3.0,6,...,1,0,2,0,0.0,0,0,0,0,NaN
46,Uruguay,Uruguay,17,29.0,55.0,3,33,270,3.0,3,...,1,2,0,1,33.3,0,0,0,0,NaN
47,Uzbekistan,Uzbekistan,22,27.4,36.5,2,22,180,2.0,1,...,2,0,0,1,50.0,0,0,0,0,NaN

In [31]:
df.isnull().sum()

time                         0
país                         0
jogadores_utilizados         0
idade_média                  0
posse_de_bola                0
                            ..
gol_pênaltis_sofridos        0
gol_pênaltis_convertidos     0
gol_pênaltis_defendidos      0
gol_pênaltis_perdidos        0
gol_pct_defesas_pênaltis    41
Length: 136, dtype: int64

In [34]:
nulos = df.isnull().sum()
nulos[nulos > 0]

penaltis_ganhos             48
penaltis_cedidos            48
penaltis_ganhos_adv         48
penaltis_cedidos_adv        48
gol_pct_defesas_pen         40
gol_pct_defesas_pênaltis    41
dtype: int64

In [37]:
Cnulos = [
    'penaltis_ganhos',
    'penaltis_cedidos',
    'penaltis_ganhos_adv',
    'penaltis_cedidos_adv',
    'gol_pct_defesas_pen',
    'gol_pct_defesas_pênaltis'
    ]

In [38]:
df[Cnulos] = df[Cnulos].fillna(0)

In [42]:
df[Cnulos].isnull().sum()

penaltis_ganhos             0
penaltis_cedidos            0
penaltis_ganhos_adv         0
penaltis_cedidos_adv        0
gol_pct_defesas_pen         0
gol_pct_defesas_pênaltis    0
dtype: int64

In [43]:
print("Duplicatas encontradas:", df.duplicated().sum())

Duplicatas encontradas: 0

In [45]:
pd.set_option('display.max_rows', None)
print(df.dtypes)

time                              object
país                              object
jogadores_utilizados               int64
idade_média                      float64
posse_de_bola                    float64
jogos                              int64
titulares                          int64
minutos                            int64
minutos_90                       float64
gols                               int64
assistencias                       int64
gols_e_assistencias                int64
gols_sem_penalti                   int64
penaltis_convertidos               int64
penaltis_cobrados                  int64
cartoes_amarelos                   int64
cartoes_vermelhos                  int64
gols_por_90                      float64
assistencias_por_90              float64
gols_assist_por_90               float64
gols_sem_pen_por_90              float64
gols_assist_sem_pen_por_90       float64
jogadores_usados_adv               int64
idade_media_adv                  float64
posse_bola_adv                   float64
jogos_adv                          int64
titulares_adv                      int64
minutos_adv                        int64
minutos_90_adv                   float64
gols_adv                           int64
assistencias_adv                   int64
gols_e_assist_adv                  int64
gols_sem_pen_adv                   int64
penaltis_conv_adv                  int64
penaltis_cobrados_adv              int64
cartoes_amarelos_adv               int64
cartoes_vermelhos_adv              int64
gols_por_90_adv                  float64
assist_por_90_adv                float64
gols_assist_por_90_adv           float64
gols_sem_pen_90_adv              float64
gols_assist_sem_pen_90_adv       float64
chutes                             int64
chutes_no_alvo                     int64
pct_chutes_no_alvo               float64
chutes_por_90                    float64
chutes_alvo_por_90               float64
gols_por_chute                   float64
gols_por_chute_no_alvo           float64
chutes_adv                         int64
chutes_no_alvo_adv                 int64
pct_chutes_no_alvo_adv           float64
chutes_por_90_adv                float64
chutes_alvo_por_90_adv           float64
gols_por_chute_adv               float64
gols_por_chute_alvo_adv          float64
minutos_por_jogo                   int64
pct_minutos_jogados                int64
minutos_por_partida_titular        int64
jogos_completos                    int64
entradas_como_sub                  int64
minutos_por_sub                    int64
reservas_nao_usados                int64
pontos_por_jogo                  float64
gols_favor_em_campo                int64
gols_contra_em_campo               int64
saldo_gols                         int64
saldo_gols_por_90                float64
minutos_por_jogo_adv               int64
pct_minutos_adv                    int64
minutos_por_titular_adv            int64
jogos_completos_adv                int64
entradas_como_sub_adv              int64
minutos_por_sub_adv                int64
reservas_nao_usados_adv            int64
pontos_por_jogo_adv              float64
gols_favor_em_campo_adv            int64
gols_contra_em_campo_adv           int64
saldo_gols_adv                     int64
saldo_gols_por_90_adv            float64
cartoes_amarelo_vermelho           int64
faltas_cometidas                   int64
faltas_sofridas                    int64
impedimentos                       int64
cruzamentos                        int64
interceptacoes                     int64
desarmes_vencidos                  int64
penaltis_ganhos                  float64
penaltis_cedidos                 float64
gols_contra                        int64
cartoes_am_verm_adv                int64
faltas_cometidas_adv               int64
faltas_sofridas_adv                int64
impedimentos_adv                   int64
cruzamentos_adv                    int64
interceptacoes_adv                 int64
desarmes_vencidos_adv              int64
penaltis_ganhos_adv              float64
penaltis_cedidos_adv             float64
gols_contra_adv                    int64
gol_jogos                          int64
gol_partidas_titular               int64
gol_minutos                        int64
gol_gols_sofridos                  int64
gol_gols_sofridos_por_90         float64
gol_finalizacoes_sofridas          int64
gol_defesas                        int64
gol_pct_defesas                  float64
gol_vitorias                       int64
gol_empates_gol                    int64
gol_derrotas_gol                   int64
gol_jogos_zerados                  int64
gol_pct_jogos_zerados            float64
gol_penaltis_enfrentados           int64
gol_penaltis_sofridos_gol          int64
gol_penaltis_parados               int64
gol_penaltis_errados_adv           int64
gol_pct_defesas_pen              float64
gol_jogos_adv                      int64
gol_partidas_titular_adv           int64
gol_minutos_adv                    int64
gol_gols_sofridos_adv              int64
gol_gols_sofridos_90_adv         float64
gol_finalizacoes_sofridas_adv      int64
gol_defesas_adv                    int64
gol_pct_defesas_adv              float64
gol_vitórias_adversário            int64
gol_empates_adversário             int64
gol_derrotas_adversário            int64
gol_jogos_sem_tomar_gol            int64
gol_pct_sem_tomar_gol            float64
gol_pênaltis_sofridos              int64
gol_pênaltis_convertidos           int64
gol_pênaltis_defendidos            int64
gol_pênaltis_perdidos              int64
gol_pct_defesas_pênaltis         float64
dtype: object

In [47]:
colunas_tipo = [
    'penaltis_ganhos',
    'penaltis_cedidos',
    'penaltis_ganhos_adv',
    'penaltis_cedidos_adv'
]

df[colunas_tipo] = df[colunas_tipo].astype(int)

In [48]:
df[colunas_tipo].dtypes

penaltis_ganhos         int64
penaltis_cedidos        int64
penaltis_ganhos_adv     int64
penaltis_cedidos_adv    int64
dtype: object

In [50]:
colunas_chave = [
    'idade_média',
    'posse_de_bola',
    'gols',
    'gols_adv',
    'gols_por_90',
    'chutes',
    'pct_chutes_no_alvo',
    'gol_pct_defesas',
    'saldo_gols',
    'pontos_por_jogo'
]

df[colunas_chave].describe()

,idade_média,posse_de_bola,gols,gols_adv,gols_por_90,chutes,pct_chutes_no_alvo,gol_pct_defesas,saldo_gols,pontos_por_jogo
count,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000
mean,28.320833,50.070833,3.854167,3.854167,1.388542,34.062500,34.108333,66.954167,0.000000,1.367292
std,1.375617,11.216818,2.617369,2.835861,0.888123,14.513979,9.295912,16.864705,4.495861,0.881145
min,25.600000,29.500000,0.000000,0.000000,0.000000,10.000000,9.500000,33.300000,-11.000000,0.000000
25%,27.275000,40.350000,2.000000,2.000000,0.670000,22.750000,27.000000,57.700000,-2.000000,0.670000
50%,28.150000,51.150000,3.000000,3.000000,1.165000,32.500000,34.100000,66.700000,0.000000,1.330000
75%,29.300000,59.775000,6.000000,5.250000,2.082500,44.250000,41.350000,77.025000,4.000000,2.000000
max,32.100000,70.500000,10.000000,11.000000,3.330000,73.000000,50.000000,100.000000,8.000000,3.000000

In [52]:
df['país'] = df['país'].str.strip().str.title()
df['time'] = df['time'].str.strip().str.title()

In [53]:
df[['time', 'país']].head(10)

             time                    país
0         Algeria                 Algeria
1       Argentina               Argentina
2       Australia               Australia
3         Austria                 Austria
4         Belgium                 Belgium
5  Bosnia & Herz.  Bosnia And Herzegovina
6          Brazil                  Brazil
7      Cabo Verde              Cape Verde
8          Canada                  Canada
9        Colombia                Colombia

In [54]:
inconsistencia_1 = df[df['gols_sem_penalti'] > df['gols']]
print("Gols sem pênalti > gols totais:", len(inconsistencia_1))

inconsistencia_2 = df[(df['posse_de_bola'] < 0) | (df['posse_de_bola'] > 100)]
print("Posse de bola fora do intervalo:", len(inconsistencia_2))

inconsistencia_3 = df[(df['gol_pct_defesas'] < 0) | (df['gol_pct_defesas'] > 100)]
print("Pct defesas fora do intervalo:", len(inconsistencia_3))

Gols sem pênalti > gols totais: 0
Posse de bola fora do intervalo: 0
Pct defesas fora do intervalo: 0